[package]
name = "doublets_gql_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = "4.0.2"
actix-web = "4"
async-graphql-actix-web = "4.0.2"
doublets = { version = "0.1.0-alpha.19", features = ["full"] }
