[package]
name = "doublets_gql_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.19", features = ["full"] }
async-std = { version = "1.12", features = ["attributes"] }
async-graphql = "4.0"
actix-web = "4.0"
async-graphql-actix-web = "4.0"
#doublets = { version = "0.1.0-alpha.20", features = ["full"] }
doublets = "0.1.0-beta.3"
