package resolvers

import (
	"context"
	"doublets-gql/generated"
)

// This file demonstrates the resolver interface that would be generated by gqlgen
// In the actual implementation, this would be auto-generated based on the GraphQL schema

// Query returns generated.QueryResolver implementation
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Mutation returns generated.MutationResolver implementation  
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Links returns generated.LinksResolver implementation
func (r *Resolver) Links() LinksResolver { return &linksResolver{r} }

// Resolver interfaces - these would be generated by gqlgen
type QueryResolver interface {
	Links(ctx context.Context, where *generated.LinksWhereInput, distinctOn []generated.LinksSelectColumn, orderBy []*generated.LinksOrderBy, offset *int, limit *int) ([]*generated.Links, error)
	Link(ctx context.Context, id string) (*generated.Links, error)
	LinksAggregate(ctx context.Context, where *generated.LinksWhereInput, distinctOn []generated.LinksSelectColumn) (*generated.LinksAggregate, error)
}

type MutationResolver interface {
	InsertLinksOne(ctx context.Context, object generated.LinksInsertInput) (*generated.Links, error)
	InsertLinks(ctx context.Context, objects []generated.LinksInsertInput) (*generated.LinksMutationResponse, error)
	UpdateLinks(ctx context.Context, set *generated.LinksSetInput, where generated.LinksWhereInput) (*generated.LinksMutationResponse, error)
	DeleteLinks(ctx context.Context, where generated.LinksWhereInput) (*generated.LinksMutationResponse, error)
}

type LinksResolver interface {
	From(ctx context.Context, obj *generated.Links) (*generated.Links, error)
	To(ctx context.Context, obj *generated.Links) (*generated.Links, error)
	Out(ctx context.Context, obj *generated.Links, where *generated.LinksWhereInput, distinctOn []generated.LinksSelectColumn, orderBy []*generated.LinksOrderBy, offset *int, limit *int) ([]*generated.Links, error)
	In(ctx context.Context, obj *generated.Links, where *generated.LinksWhereInput, distinctOn []generated.LinksSelectColumn, orderBy []*generated.LinksOrderBy, offset *int, limit *int) ([]*generated.Links, error)
}