package resolvers

import (
	"context"
	"strconv"

	"doublets-gql/generated"
)

// From resolves the from field of a Links object
// This would be generated by gqlgen to handle the relationship
func (r *linksResolver) From(ctx context.Context, obj *generated.Links) (*generated.Links, error) {
	fromID, err := strconv.ParseUint(obj.FromID, 10, 64)
	if err != nil {
		return nil, err
	}
	
	link, err := r.store.Get(ctx, fromID)
	if err != nil {
		// If the link doesn't exist, return nil (GraphQL nullable field)
		return nil, nil
	}
	
	return &generated.Links{
		ID:     strconv.FormatUint(link.ID, 10),
		FromID: strconv.FormatUint(link.FromID, 10),
		ToID:   strconv.FormatUint(link.ToID, 10),
	}, nil
}

// To resolves the to field of a Links object
func (r *linksResolver) To(ctx context.Context, obj *generated.Links) (*generated.Links, error) {
	toID, err := strconv.ParseUint(obj.ToID, 10, 64)
	if err != nil {
		return nil, err
	}
	
	link, err := r.store.Get(ctx, toID)
	if err != nil {
		// If the link doesn't exist, return nil (GraphQL nullable field)
		return nil, nil
	}
	
	return &generated.Links{
		ID:     strconv.FormatUint(link.ID, 10),
		FromID: strconv.FormatUint(link.FromID, 10),
		ToID:   strconv.FormatUint(link.ToID, 10),
	}, nil
}

// Out resolves the out field of a Links object (outgoing relationships)
func (r *linksResolver) Out(ctx context.Context, obj *generated.Links, where *generated.LinksWhereInput, distinctOn []generated.LinksSelectColumn, orderBy []*generated.LinksOrderBy, offset *int, limit *int) ([]*generated.Links, error) {
	linkID, err := strconv.ParseUint(obj.ID, 10, 64)
	if err != nil {
		return nil, err
	}
	
	// Convert GraphQL input to store filter
	filter := convertWhereInput(where)
	
	if offset != nil {
		filter.Offset = offset
	}
	if limit != nil {
		filter.Limit = limit
	}
	
	// Convert order by
	if orderBy != nil {
		filter.OrderBy = convertOrderBy(orderBy)
	}
	
	// Get outgoing links
	links, err := r.store.GetOutgoing(ctx, linkID, filter)
	if err != nil {
		return nil, err
	}
	
	// Convert to GraphQL types
	result := make([]*generated.Links, len(links))
	for i, link := range links {
		result[i] = &generated.Links{
			ID:     strconv.FormatUint(link.ID, 10),
			FromID: strconv.FormatUint(link.FromID, 10),
			ToID:   strconv.FormatUint(link.ToID, 10),
		}
	}
	
	return result, nil
}

// In resolves the in field of a Links object (incoming relationships)
func (r *linksResolver) In(ctx context.Context, obj *generated.Links, where *generated.LinksWhereInput, distinctOn []generated.LinksSelectColumn, orderBy []*generated.LinksOrderBy, offset *int, limit *int) ([]*generated.Links, error) {
	linkID, err := strconv.ParseUint(obj.ID, 10, 64)
	if err != nil {
		return nil, err
	}
	
	// Convert GraphQL input to store filter
	filter := convertWhereInput(where)
	
	if offset != nil {
		filter.Offset = offset
	}
	if limit != nil {
		filter.Limit = limit
	}
	
	// Convert order by
	if orderBy != nil {
		filter.OrderBy = convertOrderBy(orderBy)
	}
	
	// Get incoming links
	links, err := r.store.GetIncoming(ctx, linkID, filter)
	if err != nil {
		return nil, err
	}
	
	// Convert to GraphQL types
	result := make([]*generated.Links, len(links))
	for i, link := range links {
		result[i] = &generated.Links{
			ID:     strconv.FormatUint(link.ID, 10),
			FromID: strconv.FormatUint(link.FromID, 10),
			ToID:   strconv.FormatUint(link.ToID, 10),
		}
	}
	
	return result, nil
}

// Links resolver type - this would be generated by gqlgen
type linksResolver struct{ *Resolver }