package resolvers

import (
	"context"
	"strconv"

	"doublets-gql/generated"
)

// InsertLinksOne resolves the insert_links_one mutation
// This would be generated by gqlgen based on the GraphQL schema
func (r *mutationResolver) InsertLinksOne(ctx context.Context, object generated.LinksInsertInput) (*generated.Links, error) {
	fromID, err := strconv.ParseUint(object.FromID, 10, 64)
	if err != nil {
		return nil, err
	}
	
	toID, err := strconv.ParseUint(object.ToID, 10, 64)
	if err != nil {
		return nil, err
	}
	
	link, err := r.store.Create(ctx, fromID, toID)
	if err != nil {
		return nil, err
	}
	
	return &generated.Links{
		ID:     strconv.FormatUint(link.ID, 10),
		FromID: strconv.FormatUint(link.FromID, 10),
		ToID:   strconv.FormatUint(link.ToID, 10),
	}, nil
}

// InsertLinks resolves the insert_links mutation
func (r *mutationResolver) InsertLinks(ctx context.Context, objects []generated.LinksInsertInput) (*generated.LinksMutationResponse, error) {
	var returning []*generated.Links
	
	for _, object := range objects {
		fromID, err := strconv.ParseUint(object.FromID, 10, 64)
		if err != nil {
			return nil, err
		}
		
		toID, err := strconv.ParseUint(object.ToID, 10, 64)
		if err != nil {
			return nil, err
		}
		
		link, err := r.store.Create(ctx, fromID, toID)
		if err != nil {
			return nil, err
		}
		
		returning = append(returning, &generated.Links{
			ID:     strconv.FormatUint(link.ID, 10),
			FromID: strconv.FormatUint(link.FromID, 10),
			ToID:   strconv.FormatUint(link.ToID, 10),
		})
	}
	
	return &generated.LinksMutationResponse{
		AffectedRows: len(returning),
		Returning:    returning,
	}, nil
}

// UpdateLinks resolves the update_links mutation
func (r *mutationResolver) UpdateLinks(ctx context.Context, set *generated.LinksSetInput, where generated.LinksWhereInput) (*generated.LinksMutationResponse, error) {
	if set == nil {
		return &generated.LinksMutationResponse{
			AffectedRows: 0,
			Returning:    []*generated.Links{},
		}, nil
	}
	
	// First, find links that match the where clause
	filter := convertWhereInput(&where)
	links, err := r.store.Query(ctx, filter)
	if err != nil {
		return nil, err
	}
	
	var returning []*generated.Links
	
	// Update each matching link
	for _, link := range links {
		newFromID := link.FromID
		newToID := link.ToID
		
		if set.FromID != nil {
			newFromID, err = strconv.ParseUint(*set.FromID, 10, 64)
			if err != nil {
				return nil, err
			}
		}
		
		if set.ToID != nil {
			newToID, err = strconv.ParseUint(*set.ToID, 10, 64)
			if err != nil {
				return nil, err
			}
		}
		
		updatedLink, err := r.store.Update(ctx, link.ID, newFromID, newToID)
		if err != nil {
			return nil, err
		}
		
		returning = append(returning, &generated.Links{
			ID:     strconv.FormatUint(updatedLink.ID, 10),
			FromID: strconv.FormatUint(updatedLink.FromID, 10),
			ToID:   strconv.FormatUint(updatedLink.ToID, 10),
		})
	}
	
	return &generated.LinksMutationResponse{
		AffectedRows: len(returning),
		Returning:    returning,
	}, nil
}

// DeleteLinks resolves the delete_links mutation
func (r *mutationResolver) DeleteLinks(ctx context.Context, where generated.LinksWhereInput) (*generated.LinksMutationResponse, error) {
	// First, find links that match the where clause
	filter := convertWhereInput(&where)
	links, err := r.store.Query(ctx, filter)
	if err != nil {
		return nil, err
	}
	
	var returning []*generated.Links
	
	// Delete each matching link
	for _, link := range links {
		// Store the link data before deletion for the response
		returning = append(returning, &generated.Links{
			ID:     strconv.FormatUint(link.ID, 10),
			FromID: strconv.FormatUint(link.FromID, 10),
			ToID:   strconv.FormatUint(link.ToID, 10),
		})
		
		err := r.store.Delete(ctx, link.ID)
		if err != nil {
			return nil, err
		}
	}
	
	return &generated.LinksMutationResponse{
		AffectedRows: len(returning),
		Returning:    returning,
	}, nil
}

// Mutation resolver type - this would be generated by gqlgen
type mutationResolver struct{ *Resolver }