package resolvers

import (
	"context"
	"strconv"

	"doublets-gql/doublets"
	"doublets-gql/generated"
)

// Links resolves the links query
// This would be generated by gqlgen based on the GraphQL schema
func (r *queryResolver) Links(ctx context.Context, where *generated.LinksWhereInput, distinctOn []generated.LinksSelectColumn, orderBy []*generated.LinksOrderBy, offset *int, limit *int) ([]*generated.Links, error) {
	// Convert GraphQL input to store filter
	filter := convertWhereInput(where)
	
	if offset != nil {
		filter.Offset = offset
	}
	if limit != nil {
		filter.Limit = limit
	}
	
	// Convert order by
	if orderBy != nil {
		filter.OrderBy = convertOrderBy(orderBy)
	}
	
	// Query the store
	links, err := r.store.Query(ctx, filter)
	if err != nil {
		return nil, err
	}
	
	// Convert to GraphQL types
	result := make([]*generated.Links, len(links))
	for i, link := range links {
		result[i] = &generated.Links{
			ID:     strconv.FormatUint(link.ID, 10),
			FromID: strconv.FormatUint(link.FromID, 10),
			ToID:   strconv.FormatUint(link.ToID, 10),
		}
	}
	
	return result, nil
}

// Link resolves the link query for a single link
func (r *queryResolver) Link(ctx context.Context, id string) (*generated.Links, error) {
	linkID, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, err
	}
	
	link, err := r.store.Get(ctx, linkID)
	if err != nil {
		return nil, err
	}
	
	return &generated.Links{
		ID:     strconv.FormatUint(link.ID, 10),
		FromID: strconv.FormatUint(link.FromID, 10),
		ToID:   strconv.FormatUint(link.ToID, 10),
	}, nil
}

// LinksAggregate resolves the links_aggregate query
func (r *queryResolver) LinksAggregate(ctx context.Context, where *generated.LinksWhereInput, distinctOn []generated.LinksSelectColumn) (*generated.LinksAggregate, error) {
	filter := convertWhereInput(where)
	
	// Get count
	count, err := r.store.Count(ctx, filter)
	if err != nil {
		return nil, err
	}
	
	// Get actual nodes for the aggregate
	links, err := r.store.Query(ctx, filter)
	if err != nil {
		return nil, err
	}
	
	// Convert to GraphQL types
	nodes := make([]*generated.Links, len(links))
	for i, link := range links {
		nodes[i] = &generated.Links{
			ID:     strconv.FormatUint(link.ID, 10),
			FromID: strconv.FormatUint(link.FromID, 10),
			ToID:   strconv.FormatUint(link.ToID, 10),
		}
	}
	
	// Calculate min/max values
	var maxID, minID, maxFromID, minFromID, maxToID, minToID *string
	if len(links) > 0 {
		maxIDVal, minIDVal := links[0].ID, links[0].ID
		maxFromIDVal, minFromIDVal := links[0].FromID, links[0].FromID
		maxToIDVal, minToIDVal := links[0].ToID, links[0].ToID
		
		for _, link := range links[1:] {
			if link.ID > maxIDVal {
				maxIDVal = link.ID
			}
			if link.ID < minIDVal {
				minIDVal = link.ID
			}
			if link.FromID > maxFromIDVal {
				maxFromIDVal = link.FromID
			}
			if link.FromID < minFromIDVal {
				minFromIDVal = link.FromID
			}
			if link.ToID > maxToIDVal {
				maxToIDVal = link.ToID
			}
			if link.ToID < minToIDVal {
				minToIDVal = link.ToID
			}
		}
		
		maxIDStr := strconv.FormatUint(maxIDVal, 10)
		minIDStr := strconv.FormatUint(minIDVal, 10)
		maxFromIDStr := strconv.FormatUint(maxFromIDVal, 10)
		minFromIDStr := strconv.FormatUint(minFromIDVal, 10)
		maxToIDStr := strconv.FormatUint(maxToIDVal, 10)
		minToIDStr := strconv.FormatUint(minToIDVal, 10)
		
		maxID = &maxIDStr
		minID = &minIDStr
		maxFromID = &maxFromIDStr
		minFromID = &minFromIDStr
		maxToID = &maxToIDStr
		minToID = &minToIDStr
	}
	
	return &generated.LinksAggregate{
		Aggregate: &generated.LinksAggregateFields{
			Count: int(count),
			Max: &generated.LinksMaxFields{
				ID:     maxID,
				FromID: maxFromID,
				ToID:   maxToID,
			},
			Min: &generated.LinksMinFields{
				ID:     minID,
				FromID: minFromID,
				ToID:   minToID,
			},
		},
		Nodes: nodes,
	}, nil
}

// Helper functions to convert GraphQL inputs to store types

func convertWhereInput(where *generated.LinksWhereInput) *doublets.QueryFilter {
	if where == nil {
		return &doublets.QueryFilter{}
	}
	
	filter := &doublets.QueryFilter{}
	
	if where.ID != nil {
		filter.ID = convertIDFilter(where.ID)
	}
	if where.FromID != nil {
		filter.FromID = convertIDFilter(where.FromID)
	}
	if where.ToID != nil {
		filter.ToID = convertIDFilter(where.ToID)
	}
	
	if where.And != nil {
		filter.And = make([]*doublets.QueryFilter, len(where.And))
		for i, andWhere := range where.And {
			filter.And[i] = convertWhereInput(andWhere)
		}
	}
	
	if where.Or != nil {
		filter.Or = make([]*doublets.QueryFilter, len(where.Or))
		for i, orWhere := range where.Or {
			filter.Or[i] = convertWhereInput(orWhere)
		}
	}
	
	if where.Not != nil {
		filter.Not = convertWhereInput(where.Not)
	}
	
	return filter
}

func convertIDFilter(idComp *generated.IDComparisonExp) *doublets.IDFilter {
	if idComp == nil {
		return nil
	}
	
	filter := &doublets.IDFilter{}
	
	if idComp.Eq != nil {
		val, _ := strconv.ParseUint(*idComp.Eq, 10, 64)
		filter.Eq = &val
	}
	if idComp.Neq != nil {
		val, _ := strconv.ParseUint(*idComp.Neq, 10, 64)
		filter.Neq = &val
	}
	if idComp.Gt != nil {
		val, _ := strconv.ParseUint(*idComp.Gt, 10, 64)
		filter.Gt = &val
	}
	if idComp.Gte != nil {
		val, _ := strconv.ParseUint(*idComp.Gte, 10, 64)
		filter.Gte = &val
	}
	if idComp.Lt != nil {
		val, _ := strconv.ParseUint(*idComp.Lt, 10, 64)
		filter.Lt = &val
	}
	if idComp.Lte != nil {
		val, _ := strconv.ParseUint(*idComp.Lte, 10, 64)
		filter.Lte = &val
	}
	if idComp.In != nil {
		filter.In = make([]uint64, len(idComp.In))
		for i, idStr := range idComp.In {
			filter.In[i], _ = strconv.ParseUint(idStr, 10, 64)
		}
	}
	if idComp.Nin != nil {
		filter.Nin = make([]uint64, len(idComp.Nin))
		for i, idStr := range idComp.Nin {
			filter.Nin[i], _ = strconv.ParseUint(idStr, 10, 64)
		}
	}
	
	return filter
}

func convertOrderBy(orderBy []*generated.LinksOrderBy) []*doublets.OrderBy {
	result := make([]*doublets.OrderBy, 0)
	
	for _, ob := range orderBy {
		if ob.ID != nil {
			result = append(result, &doublets.OrderBy{
				Field:     "id",
				Direction: convertDirection(*ob.ID),
			})
		}
		if ob.FromID != nil {
			result = append(result, &doublets.OrderBy{
				Field:     "from_id",
				Direction: convertDirection(*ob.FromID),
			})
		}
		if ob.ToID != nil {
			result = append(result, &doublets.OrderBy{
				Field:     "to_id",
				Direction: convertDirection(*ob.ToID),
			})
		}
	}
	
	return result
}

func convertDirection(dir generated.OrderByDirection) doublets.Direction {
	switch dir {
	case generated.OrderByDirectionAsc:
		return doublets.DirectionAsc
	case generated.OrderByDirectionDesc:
		return doublets.DirectionDesc
	default:
		return doublets.DirectionAsc
	}
}

// Query resolver type - this would be generated by gqlgen
type queryResolver struct{ *Resolver }