package resolvers

import (
	"doublets-gql/doublets"
)

// Resolver is the root resolver for the GraphQL schema
// This would typically be generated by gqlgen but is shown here for demonstration
type Resolver struct {
	store doublets.Store
}

// NewResolver creates a new resolver with the provided store
func NewResolver(store doublets.Store) *Resolver {
	return &Resolver{
		store: store,
	}
}